%MACRO DATAS(LIBNAME, PLANILHAS, PREFIXO);
  %*PEGA TODAS AS TABELAS DA LIBNAME;
  PROC SQL;
    CREATE TABLE DATAS_BASES AS
      SELECT MEMNAME, MODATE
      FROM SASHELP.VTABLE
      WHERE LIBNAME = "&LIBNAME"
    ;
  QUIT;

  %*PERCORRE TODAS AS PLANILHAS PASSADAS POR PARÂMETRO, IDENTIFICANDO A MAIOR DATA E SALVANDO NA VARIAVEL DATA_PLANILHA;
  %LOCAL I PLANILHA DATA_AUX;
  %LET I=1;
  %DO %WHILE (%SCAN(&PLANILHAS, %I) NE);
    %LET PLANILHA = %SCAN(PLANILHAS, %I);
    %PUT &PLANILHA;

    %GLOBAL DATA_%PLANILHA.;
    %LET DATA_AUX = ERROR;

    PROC SQL OUTOBS=1 NOPRINT;
      SELECT COMPRESS(SUBSTR(MEMNAME, LENGTH(MEMNAME) -7, 8)) INTO: DATA_AUX
      FROM DATA_BASES
      WHERE PRXMATCH(CAT("!\b&PREFIXO", "&PLANILHA", '_\d{8}\b!'), COMPRESS(MEMNAME)) > 0
      ORDER BY MEMNAME DESC
      ;
    QUIT;

      %LET DATA_&PLANILHA. = &DATA_AUX.;
      %LET I = %EVAL(&I + 1);
  %END;

  %*APAGA A BASE AUXILIAR PARA USAR NOVAMENTE NO LOOPING;
  PROC SQL;
    DROP TABLE DATA_BASES;
  QUIT;
%MEND;


%*DEFINIÇÃO DOS NOMES DAS BASES;
%LET BASES = (COLOCAR OS NOMES DAS BESES COM VIRGULA)
;

%*CHAMANDO A MACRO;
DATAS (
  LIBNAME = (NOME DA LIBNAME),
  PLANILHAS = &BASES.,
  PREFIXO = (SE EXISITIR UM PREFIXO ANTES DE CADA BASES, IMPORTANTE LEMBRAR QUE TEM QUE SER O MESMO PREFIXO)
  );
